---
- name: Launch database
  docker_container:
    name: database
    image: daddyornot/tp-devops-database
    state: started
    recreate: true
    pull: true
    networks:
      - name: "{{ docker_network_name }}"
    env:
      # POSTGRES_USER: "'{{ lookup('env', 'POSTGRES_USER') }}'" 
      # POSTGRES_PASSWORD: "'{{ lookup('env', 'POSTGRES_PASSWORD') }}'"
      # POSTGRES_DB: "'{{ lookup('env', 'POSTGRES_DB') }}'"
      POSTGRES_USER: "{{ POSTGRES_USER }}" 
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"




