---
- name: Launch database
  docker_container:
    name: "{{ db_container_name }}"
    image: daddyornot/tp-devops-database
    state: started
    recreate: true
    pull: true
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - data:/var/lib/postgresql/data
    env:
      POSTGRES_USER: "{{ POSTGRES_USER }}" 
      POSTGRES_PASSWORD: "{{ POSTGRES_PASSWORD }}"
      POSTGRES_DB: "{{ POSTGRES_DB }}"




