---
- name: Launch front
  docker_container:
    name: front
    image: daddyornot/tp-devops-front
    state: started
    recreate: true
    pull: true
    networks:
      - name: "{{ docker_network_name }}"
