---
- name: Launch front
  docker_container:
    name: front
    image: daddyornot/tp-devops-frontend
    state: started
    recreate: true
    networks:
      - name: "{{ docker_network_name }}"
    ports: 
      - "80:80"
