version: '3.8'

services:
    api:
        container_name: api
        build: 
            context: spring/simple-api-student
            dockerfile: Dockerfile
        networks: 
          - tp1-network
        depends_on:
          - database
        env_file:
          - .env

    database:
        container_name: database
        build:
            context: database
            dockerfile: Dockerfile
        networks:
         - tp1-network
        env_file:
          - .env
        volumes:
          - ./data:/var/lib/postgresql/data

    web:
        container_name: web
        build:
            context: httpd
            dockerfile: Dockerfile
        ports: 
          - "8080:80"
        networks:
          - tp1-network
        depends_on:
          - api

networks:
    tp1-network:
