---
- name: Launch api
  docker_container:
    name: api
    image: daddyornot/tp-devops-simple-api
    state: started
    recreate: true
    pull: true
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "8080:8080"

    env_file: '{{ path_env_file }}/.env'

