- hosts: all
  gather_facts: false
  become: true
  vars: 
    ansible_user: "centos"
    docker_network_name: "api-network"
    db_container_name: "database"
    api_container_name: "api"
    proxy_container_name: "web"
    front_container_name: "front"

  roles:
    - docker
    - network
    - database
    - app
    - proxy
    - front
