name: Build and Push to DockerHub
on:
  workflow_run:
    workflows: ["Test Backend and Sonar Analysis"]
    types: [completed]
    branches:
      - 'main'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build image and push backend
      #   uses: docker/build-push-action@v3
      #   with:
      #     # relative path to the place where source code with Dockerfile is located
      #     context: ./simple-api-student
      #     # Note: tags has to be all lower-case
      #     tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-simple-api:latest
      #     # build on feature branches, push only on main branch
      #     push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Build image and push database
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./database
      #     tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-database:latest
      #     push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Build image and push httpd
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./httpd
      #     tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-httpd:latest
      #     push: ${{ github.ref == 'refs/heads/main' }}

      # - name: Build image and push frontend
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: ./devops-front
      #     tags:  ${{secrets.DOCKERHUB_USERNAME}}/tp-devops-front:latest
      #     push: ${{ github.ref == 'refs/heads/main' }}

  on-failure-echo:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'Test Backend and Sonar Analysis has failed'

