name: Test Backend and Sonar Analysis
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
     #checkout your github code using actions/checkout@v2.5.0
      - name: Checkout code
        uses: actions/checkout@v2.5.0

     #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3 
        with:
          java-version: '17'
          distribution: 'adopt'

    #  finally build your app with the latest command
      - name: Build and test with Maven
        working-directory: ./simple-api-student
        run: |
              mvn clean install 
              mvn -B verify sonar:sonar -Dsonar.projectKey=tp-devops-cpe-2024_simple-api -Dsonar.organization=tp-devops-cpe-2024 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml

